name: flutter_my_tracker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1
  location_permissions: ^4.0.1
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  background_locator_2: ^2.0.6
  path: ^1.8.3
  logger: ^2.0.2+1
  ditredi: ^2.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  pedometer: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  

flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true
