name: flutter_my_tracker
description: A new Flutter project.
publish_to: none
version: 1.0.1+5
authorsName: Kuloud

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  background_locator:
    git:
      url: git@github.com:kuloud/background_locator_fixed.git
      ref: master
  path: ^1.8.3
  logger: ^2.0.2+1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  shared_preferences: ^2.2.2
  injectable: ^2.3.2
  fl_chart: ^0.64.0
  permission_handler: ^11.0.1
  ditredi: ^2.0.0
  vector_math: ^2.1.4
  about: ^2.1.3
  image_gallery_saver:
    git:
      url: git@github.com:kuloud/image_gallery_saver.git
      ref: master
  share: ^2.0.4
  app_settings: ^5.1.1
  url_launcher: ^6.2.1
  sensors_plus: ^4.0.0
  matrices: ^1.2.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  pubspec_extract: ^2.0.5
  

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/app_logo.png
    - PRIVACY-POLICY.md
    - PRIVACY-POLICY-zh_CN.md
    - CHANGELOG.md
    - CHANGELOG-zh_CN.md
    - README.md
    - README-zh_CN.md
flutter_intl:
  enabled: true
