on:
  push:
    branches:
      - main
  workflow_dispatch:
  
name: Build
jobs:

  # analyze:
  #   name: analyze
  #   runs-on: ubuntu-latest
  #   environment: flove
  #   container: 
  #     image: ghcr.io/kuloud/flutter-essentials-docker:main
  #     options: --user root
  #     credentials:
  #       username: ${{ github.actor }}
  #       password: ${{ secrets.REPO_TOKEN }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/flutter-analyze

  # test:
  #   name: test
  #   runs-on: ubuntu-latest
  #   environment: flove
  #   container: 
  #     image: ghcr.io/kuloud/flutter-essentials-docker:main
  #     options: --user root
  #     credentials:
  #       username: ${{ github.actor }}
  #       password: ${{ secrets.REPO_TOKEN }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/flutter-test

  android-release-build:
    name: android-release-build
    runs-on: ubuntu-latest
    environment: flove
    # needs: [test, analyze]
    container: 
      image: ghcr.io/kuloud/flutter-essentials-docker:main
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory /home/developer/flutter
      - uses: NiklasLehnfeld/flutter-android-build-action@v1
        id: android-build
        with:
          release: false
          keystore: ${{ secrets.KEYSTORE }}
          keystore-pwd: "${{ secrets.NETZPOLITIK_KEYSTORE_PWD }}"
          key-pwd: "${{ secrets.NETZPOLITIK_KEY_PWD }}"
      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: ${{ steps.android-build.outputs.apk-path }}
      - name: Archive AAB
        uses: actions/upload-artifact@v2
        with:
          name: release-aab
          path: ${{ steps.android-build.outputs.aab-path }}

  create-github-release:
    name: create-github-release
    runs-on: ubuntu-latest
    environment: flove
    needs: [android-release-build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v2
        with:
          name: release-apk
      - uses: actions/download-artifact@v2
        with:
          name: release-aab
      - id: version
        uses: NiklasLehnfeld/flutter-version-number-action@v1
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.REPO_TOKEN }}
          prerelease: false
          automatic_release_tag: ${{ steps.version.outputs.version-number }}
          title: ${{ steps.version.outputs.version-number }}
          files: |
            *.apk
            *.aab
